branches:
only:
    - dev
language: python
python:
    - "2.7"
    - "pypy"
install:
    - pip install -r scripts/requirements.txt --use-mirrors
before_script:
    - mysql -e 'create database hackdo;'
    - mysql -e 'create database hackdo_test;'
    - 'flake8 --exclude=migrations --ignore=E501,F403 --statistics .'
script:
    - python manage.py test hado
notifications:
    email:
    recipients:
        - wgx731@gmail.com
