language: python

python:
    - "2.7"

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - pip install -r requirements.txt --use-mirrors

before_script:
    - mysql -u root < scripts/hackdo.sql
    - "flake8 --exclude=migrations --ignore=E501,F403 --statistics .;"

script:
    - python manage.py test hado
    - python manage.py harvest --settings=test_settings --verbosity=2
